<h4><strong>Bug-Fixing Exercise 1</strong></h4><p>Have a look at the program below:</p><pre class="prettyprint linenums">waiting_list = ["john", "marry"]
name = input("Enter name: ")

number = waiting_list.index(name)
print(f"{name}'s turn is {number}")</pre><p>&nbsp; &nbsp;</p><p>When the user enters the name of one of the <code>waiting_list</code> members, the program returns the index of that name. For example, when the user enters "john", 0 is printed out.</p><p><br></p><figure><img height="42" src="https://img-c.udemycdn.com/redactor/raw/article_lecture/2022-11-16_20-02-05-510a2388ceaed6a3bc3ed4ee7aad4a44.png" width="301"></figure><p> If the user enters a name that is not in the list, such as "zen", the program throws an error. </p><figure><img height="178" src="https://img-c.udemycdn.com/redactor/raw/article_lecture/2022-05-19_16-27-30-6531b31467012ecbb3732397c4c38ef7.png" width="674"></figure><p>Change the program, so it prints out "zen is not in the list" instead of returning an error when the user enters "zen" or any other name that is not in the list.</p><p><a href="https://pythonhow.com/bug-fixing/d10b1/" rel="noopener noreferrer" target="_blank">Solution</a></p>